pipeline {
    agent any
    options {
        timeout(time: 100, unit: 'SECONDS')
    }
    stages {
        stage('NareshNaidu') {
            steps {
                echo 'hello naresh'
            }
        }
        stage('Naidu') {
            steps {
                echo 'naidunaresh'
            }
        }    
    }
    post {
        failure {
            echo 'above mentioned pipeline is failure'
        }
    }
}