pipeline {
    agent any
    options {
        timeout(time: 100, unit: 'SECONDS')
    }
    stages {
        stage('NareshNaidu') {
            steps {
                echo 'hello naresh'
            }
        }
        stage('Naidu')
            steps {
                echo 'naidu naresh'
            }
    }
    post {
        success {
            echo 'above mentioned pipeline is success'
        }
    }
}