pipeline {
    agent any
    options {
        timeout(time: 100, unit: 'SECONDS')
    }
    stages {
        stage('NareshNaidu') {
            steps {
                sh "echo 'hello naresh'"
            }
        }
    }
    post {
        success {
            echo 'above mentioned pipeline is success'
        }
    }
}