pipeline {
    agent any
    parameters {
        string(name: 'PERSON', defaultValue: 'Naresh', description: 'To Whom should I say hello?')

        text(name: 'BIOGRAPHY', defaultValue: 'Myself Naresh', description: 'Enter some information about the person')

        booleanParam(name: 'TOGGLE', defaultValue: false, description: 'Toggle this value')

        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three', 'four'], description: 'Pick something')

        password(name: 'PASSWORD', defaultValue: 'N@resh@12345', description: 'Enter a password')
}
    stages {
        stage('NareshNaidu') {
            steps {
                 echo "Hello ${params.PERSON}"

                echo "Biography: ${params.BIOGRAPHY}"

                echo "Toggle: ${params.TOGGLE}"

                echo "Choice: ${params.CHOICE}"

                echo "Password: ${params.PASSWORD}"
            }
        }

    }
}