// pipeline {
//     agent any
//     parameters {
//         string(name: 'PERSON', defaultValue: 'Naresh', description: 'To Whom should I say hello?')

//         text(name: 'BIOGRAPHY', defaultValue: 'Myself Naresh', description: 'Enter some information about the person')

//         booleanParam(name: 'TOGGLE', defaultValue: false, description: 'Toggle this value')

//         choice(name: 'CHOICE', choices: ['One', 'Two', 'Three', 'four'], description: 'Pick something')

//         password(name: 'PASSWORD', defaultValue: 'N@resh@12345', description: 'Enter a password')
// }
//     stages {
//         stage('NareshNaidu') {
//             steps {
//                  echo "Hello ${params.PERSON}"

//                 echo "Biography: ${params.BIOGRAPHY}"

//                 echo "Toggle: ${params.TOGGLE}"

//                 echo "Choice: ${params.CHOICE}"

//                 echo "Password: ${params.PASSWORD}"
//             }
//         }

//     }
pipeline {
    agent any
    stages {
        stage('example') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }
            }    
                steps {
                    echo "Hello, ${PERSON}, nice to meet you."
                }

        }
    }
}    

        // stage('Approval'){
        //     input {
        //         message "Should we continue?"
        //         ok "Yes, we should."
        //         submitter "alice,bob"
        //         parameters {
        //             string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        //         }
        //     }
        //     steps {
        //         echo "Hello, ${PERSON}, nice to meet you."
        //     }
        // }